# Generated by Django 5.2.5 on 2025-08-31 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionRequest',
        ),
    ]
